INSERT INTO users (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('user', '$2a$10$IQGf0A7HvQnBCUtu/0h7be3VqY1.cBijfpN.z/tnWkxQYiAI8JRAm', true, 'Jack');
INSERT INTO users (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('admin', '$2a$10$9hzrhVjwIoWcAzwSy3P7S.O8YEQcBXSsVUuwD4spZ9RHbmRi7pPDa', true, 'Jill');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('user', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('admin', 'ROLE_ADMIN');